### PR TITLE
Add --resource flag to select pods by resource

### PR DESCRIPTION
**Pull request by tksm**
Fixes https://github.com/stern/stern/issues/159

This PR adds `--resource` flag to select pods by the specified resource in the form "\<resource\>/\<name\>".

This will be useful when we want to distinct pods created by multiple deployments whose names are partly the same.

```
$ kubectl get deploy -n kube-system | grep cert-manager
cert-manager                             1/1     1            1           61d
cert-manager-cainjector                  1/1     1            1           61d
cert-manager-webhook                     1/1     1            1           61d

# It is not easy to select only pods created by `deployment/cert-manager` with pod-query.
$ stern -n kube-system --tail 0 cert-manager
+ cert-manager-webhook-d5568c87d-tcq6g › cert-manager
+ cert-manager-84bd74df78-zb28x › cert-manager
+ cert-manager-cainjector-6dd88998fb-wpb8h › cert-manager

# The resource flag allows users to select only pods created by `deployment/cert-manager`.
$ stern -n kube-system --tail 0 --resource deploy/cert-manager
+ cert-manager-84bd74df78-zb28x › cert-manager
```

It could be the first argument in the form "\<resource\>/\<regexp\>" instead of adding the flag as in https://github.com/stern/stern/issues/159#issuecomment-922684992. But the flag with the exact match is much simpler, so I implemented it as a flag.

### CODE REVIEW

**Comment by superbrothers** [comment]
I'll check this later😍 Thanks!

**Comment by tksm** [comment]
Sorry, I found cron jobs can have no labels. I will add an error handling case when their labels are empty.

**Comment by tksm** [comment]
I added an error handling the case when labels are empty in https://github.com/stern/stern/pull/206/commits/7b9aebc69c782b997f3a75855f03b9a5526399c5 .

```
$ stern --resource cronjob/hello
Error: resource cronjob/hello has no labels
```

**Comment by tksm** [comment]
I will create another PR for a dynamic completion of `--resource` if this PR is approved. It will work like the demo below.

[asciicast](https://asciinema.org/a/uNoMy4K4pk9Lr6UlK1p41uvzq)

**Comment by superbrothers** [comment]
This is a great addition. Thank you.

I have one point I would like to discuss. Whether or not to add `--resource` flag. Currently the argument is pod-query, but if it contains `/` it can also be considered a resource.

```console
# pod-query
stern nginx

# resource
stern deployment/nginx
```

I'm not sure if adding the `--resource` flag would be clearer. What do you think?

**Comment by tksm** [comment]
@superbrothers Though it is easier to use to take a resource as the first argument indeed, I prefer it as a flag because users might expect it to take a regular expression when in the first argument.

```
stern "deployment/app.*"
```

Since it is an exact match and works as a label selector like `--selector`, I think it is natural to be a flag.

**Comment by tksm** [comment]
>  I prefer it as a flag because users might expect it to take a regular expression when in the first argument.

@superbrothers On second thought, I realized the situation when users use a regular expression for a deployment is already covered by the pod query. Since it is a new feature and the current flag is mutually exclusive with the pod query, I will reconsider it as the first argument.

**Comment by tksm** [comment]
@superbrothers After reimplementing it as the first argument, I feel `stern <resource>/<name>` is more comfortable than a flag. If you have no objection, I will close this PR and make a new PR to support a resource as the argument.

Thank you for your proposal. 👍

**Comment by superbrothers** [comment]
I have no objection. You can re-create a PR or make changes to this PR. I'm fine with either.

**Comment by tksm** [comment]
I reimplemented it as a query with some fixes in https://github.com/stern/stern/pull/208.

**Pull request closed without merging**
