### PR TITLE
Add field selector

### PR DESCRIPTION
**Pull request by uesyn**
Add field selector similar to `kubectl get --field-selector`.
This PR make log filter more flexible.

### CODE REVIEW

**Review by superbrothers — APPROVED** [review]
Nice! 🍺

**Review by superbrothers — COMMENTED** [review]
Could you add a new flag to the flag list in README.md? In addition, it would be nice if you could add an example to the Examples section.

**Comment by uesyn** [comment]
@superbrothers 
Added this flag into flag list and example!

**Comment by uesyn** [comment]
I missed to fix argument validation.
Fixed it.

**Review by superbrothers — APPROVED** [review]
:100:

**Pull request merged**
