### PR TITLE
Documenting how to get Bash completion in Krew mode

### PR DESCRIPTION
**Pull request by jglick**
Did not seem to be considered in #170.

### CODE REVIEW

**Review by rkmathi — APPROVED** [review]
Thank you!😃

**Comment by rkmathi** [comment]
@superbrothers 
This PR looks similar to #193.
Could you please tell me how to merge it? :bow:

**Comment by tksm** [comment]
@rkmathi @superbrothers #241 probably will fix the problem that we cannot merge PRs that only change README.md.

**Comment by rkmathi** [comment]
@tksm Thank you!! 😄

**Pull request merged**
